apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dojos.sample.operator.com
spec:
  group: sample.operator.com
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: string
            status:
              type: object
              properties:
                status:
                  type: string
  scope: Namespaced
  names:
    kind: Dojo
    plural: dojos
    singular: dojo
